permalink: /posts/:title
markdown: kramdown

gems:
  - jekyll-sitemap

name: Banana Bread du Jour
url: https://bananabreaddujour.com
description: Mostly about all the times I make banana bread
twitter: no twitters, my guy
